# Generated by Django 3.1.4 on 2020-12-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='except_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
