# Generated by Django 3.1.4 on 2020-12-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_except_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadFoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('info', models.TextField(blank=True, null=True)),
                ('profile_img', models.FileField(blank=True, null=True, upload_to='')),
                ('head_btn', models.CharField(blank=True, max_length=256, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('quest', models.CharField(blank=True, max_length=256, null=True)),
                ('foot_btn', models.CharField(blank=True, max_length=256, null=True)),
                ('foot_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('foot_info', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'HeadFoot Item',
                'verbose_name_plural': 'HeadFoot Items',
            },
        ),
    ]
