# Generated by Django 3.1.4 on 2020-12-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_headfoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='headfoot',
            name='photo_class',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
